### PR TITLE
Clean build artifacts from the repository.

### PR DESCRIPTION
**Pull request by BrendanLeber**
Many files were commited that should not be included ins ource control.
This commit removes those files, everything listed under the "make
clean" entry in the Makefile.  It also adds these files to .gitignore so
that they will not be flagged by git as needing to be commited.

73 de N0BML

### CODE REVIEW

**Comment by BrendanLeber** [comment]
My first PR.  :)

**Comment by TemporarilyOffline** [comment]
Thanks for posting this.  The `iambic.hex` file is the "product" and some people have expressed that they don't know how to compile that.  What's the over/under on keeping that file in the repo?

I'd like to use the "proper method" for distributing the "product".  Thoughts?

**Comment by BrendanLeber** [comment]
I wouldn't commit it to the repository.  I would "create a release" and include that as one of the files in the release.

**Comment by TemporarilyOffline** [comment]
Sounds good to me.  And sounds like that is the next step.  Merging!

**Pull request merged**
